### ISSUE TITLE
Circle of fifths screen is empty on Linux

### ISSUE THREAD

**Issue by sreich** [la-jarre-a-son/midi-jar#13] opened 2022-12-17 22:05 UTC
I can send screenshots but basically, the whole circle of fifth screen doesn't have the graphic visible on Linux. Linux. I can see it on Windows but the graph is not here on Linux. 
## Your Environment
Arch Linux, kde

- MIDI Jar version:
- Operating System:
- Hardware Devices:

**Comment by ArTiSTiX** [comment] 2022-12-20 07:20
@sreich Thanks for the feedback.

Unfortunately, i am not an user or Arch Linux, so i cannot test in the same environement as you right now.
It's working well on Ubuntu 22.04.

Can you check in the settings that you at least some sections of the circle are enabled (it's a feature to be able to display none 😅)?

Otherwise, that's strange that the svg is rendering correctly for the keyboard, but not for the circle. This might be an issue with the sizing of the circle.

Can you also check if your browser correctly renders it ? (normally when the "overlay" server is enabled, you can browse MIDI jar features externally via http://localhost:25011/circle-of-fifths)

**Comment by ArTiSTiX** [comment] 2022-12-20 12:30
@sreich mmh ok, so i think what is not working is i might have messed up settings migrations between versions.
The settings displayed here are not the settings that are taken into account.
Try reset to defaults, or toggling all settings to have them back to the expected value.

(i see that because, the "MAIN SCALE" setting is disabled here, while it should be enabled since it let you choose which of the major or the minor section is displayed first, disable if one of the two setting above it is disabled itself...)

And this little arrow is supposed to be at the center of the circle, but it has the right size, so it's not a sizing issue.
i can reproduce the same rendering if I disable all settings).

Strange bug.

**Comment by sreich** [comment] 2022-12-20 12:35
excellent, you nailed it, that was the issue. I'm glad it was a quick fix, thanks :)

**Comment by ArTiSTiX** [comment] 2022-12-20 14:02
I'll let the bug ticket open since this is a migration / initialization issue that better be addressed.

**Comment by ArTiSTiX** [comment] 2023-06-20 16:00
I think this is fixed now, so closing.

**Closed by ArTiSTiX** 2023-06-20 16:00 UTC
Labels: bug
